dataset_size: 100
number_of_iteration: 1000
exec_path: "./main"
parallel_job_size: 1
param_list:
  - name: start_temperature
    type: float
    range_from: 10
    range_to: 100
    scale: log
  - name: end_temperature
    type: float
    range_from: 0.1
    range_to: 20
    scale: log
  - name: opt2_rate
    type: float
    range_from: 0.2
    range_to: 0.8
    scale: linear
  - name: best_overwritten_frequency
    type: int
    range_from: 256
    range_to: 8192
    scale: log
  - name: input_data
    type: dataset
    template: "../../rust/tools/in/{}.txt"
    is_redirect: true
