dataset_template: "../data/in/{:04}.txt"
number_of_iteration: 500
dataset_size: 100
exec_path: "./main"
parallel_job_size: 1
param_list:
  - name: reverse_temperature
    type: float
    range_from: 0.1
    range_to: 20.0
    scale: log
  - name: beam_width
    type: int
    range_from: 5
    range_to: 20
    scale: linear
