dataset_size: 5
number_of_iteration: 30
exec_path: "./main"
parallel_job_size: 1
minimize: true
param_list:
  - name: temp
    type: string
    value: hoge
  - name: reverse_temperature
    type: float
    range_from: 1e-8
    range_to: 1e-1
    scale: log
  - name: max_diff_rate
    type: int
    range_from: 20
    range_to: 200
    scale: linear
  - name: input_data
    type: dataset
    data_dir: "tests/dataset/"
    filename: "{}.txt"
    is_redirect: true
