name: GitHub Actions Demo
on: [push]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install pytest
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pytest tests
